using System.ComponentModel;

namespace DiGi.GIS.Enums
{
    public enum BuildingSpecificFunction
    {
        [Description("pharmacy")] pharmacy,
        [Description("archive")] archive,
        [Description("remand prison")] remand_prison,
        [Description("shepherd's hut")] shepherds_hut,
        [Description("bank")] bank,
        [Description("swimming pool")] swimming_pool,
        [Description("library")] library,
        [Description("utility building")] utility_building,
        [Description("single-family building")] single_family_building,
        [Description("railway traffic control building")] railway_traffic_control_building,
        [Description("air traffic control building")] air_traffic_control_building,
        [Description("zoo or botanical garden building")] zoo_or_botanical_garden_building,
        [Description("livestock production building")] livestock_production_building,
        [Description("shipping building")] shipping_building,
        [Description("multi-family building")] multi_family_building,
        [Description("cemetery buildings")] cemetery_buildings,
        [Description("shopping center")] shopping_center,
        [Description("information center")] information_center,
        [Description("conference center")] conference_center,
        [Description("telecommunications center")] telecommunications_center,
        [Description("Orthodox church")] orthodox_church,
        [Description("cold storage")] cold_storage,
        [Description("homeless shelter")] homeless_shelter,
        [Description("children's home")] childrens_home,
        [Description("cultural center")] cultural_center,
        [Description("summer house")] summer_house,
        [Description("social care home")] social_care_home,
        [Description("parish house")] parish_house,
        [Description("funeral home")] funeral_home,
        [Description("retreat house")] retreat_house,
        [Description("student dormitory")] student_dormitory,
        [Description("department store")] department_store,
        [Description("wedding house")] wedding_house,
        [Description("holiday house")] holiday_house,
        [Description("monastery house")] monastery_house,
        [Description("camping cabin")] camping_cabin,
        [Description("bus station")] bus_station,
        [Description("train station")] train_station,
        [Description("airport terminal")] airport_terminal,
        [Description("bell tower")] bell_tower,
        [Description("combined heat and power plant")] combined_heat_power_plant,
        [Description("power plant")] power_plant,
        [Description("grain elevator")] grain_elevator,
        [Description("philharmonic hall")] philharmonic_hall,
        [Description("art gallery")] art_gallery,
        [Description("garage")] garage,
        [Description("sports hall")] sports_hall,
        [Description("market hall")] market_hall,
        [Description("arena")] arena,
        [Description("exhibition hall")] exhibition_hall,
        [Description("indoor go-kart track")] indoor_go_kart_track,
        [Description("hangar")] hangar,
        [Description("hypermarket or supermarket")] hypermarket_or_supermarket,
        [Description("hospice")] hospice,
        [Description("hotel")] hotel,
        [Description("workers' hotel")] workers_hotel,
        [Description("other educational facility")] other_educational_facility,
        [Description("other religious building")] other_religious_building,
        [Description("other public administration office")] other_public_administration_office,
        [Description("boarding school or dormitory")] boarding_school_dormitory,
        [Description("sobering-up station")] sobering_up_station,
        [Description("emergency medical service unit")] emergency_medical_service_unit,
        [Description("port authority office")] port_authority_office,
        [Description("chapel")] chapel,
        [Description("casino")] casino,
        [Description("cinema")] cinema,
        [Description("monastery")] monastery,
        [Description("veterinary clinic")] veterinary_clinic,
        [Description("sports club")] sports_club,
        [Description("club, disco")] club_disco,
        [Description("tennis courts")] tennis_courts,
        [Description("barracks")] barracks,
        [Description("church")] church,
        [Description("boiler room")] boiler_room,
        [Description("crematorium")] crematorium,
        [Description("bowling alley")] bowling_alley,
        [Description("metropolitan curia")] metropolitan_curia,
        [Description("lighthouse")] lighthouse,
        [Description("forester's lodge")] foresters_lodge,
        [Description("locomotive depot or carriage shed")] locomotive_depot_carriage_shed,
        [Description("warehouse")] warehouse,
        [Description("mosque")] mosque,
        [Description("ministry building")] ministry_building,
        [Description("mill")] mill,
        [Description("motel")] motel,
        [Description("museum")] museum,
        [Description("car wash")] car_wash,
        [Description("observatory or planetarium")] observatory_or_planetarium,
        [Description("opera house")] opera_house,
        [Description("social welfare center")] social_welfare_center,
        [Description("training and leisure center")] training_leisure_center,
        [Description("multi-story parking garage")] multi_story_parking_garage,
        [Description("commercial-service building")] commercial_service_building,
        [Description("garden pavilion or orangery")] garden_pavilion_orangery,
        [Description("guesthouse")] guesthouse,
        [Description("research facility")] research_facility,
        [Description("diplomatic or consular office")] diplomatic_or_consular_office,
        [Description("healthcare facility")] healthcare_facility,
        [Description("postal operator's office")] postal_operators_office,
        [Description("care and educational facility")] care_educational_facility,
        [Description("police station")] police_station,
        [Description("production building")] production_building,
        [Description("prosecutor's office")] prosecutors_office,
        [Description("kindergarten")] kindergarten,
        [Description("border crossing")] border_crossing,
        [Description("refinery")] refinery,
        [Description("restaurant")] restaurant,
        [Description("ambassador's residence")] ambassadors_residence,
        [Description("bishop's residence")] bishops_residence,
        [Description("presidential residence")] presidential_residence,
        [Description("gym")] gym,
        [Description("solarium")] solarium,
        [Description("court building")] court_building,
        [Description("juvenile shelter")] juvenile_shelter,
        [Description("animal shelter")] animal_shelter,
        [Description("tourist shelter")] tourist_shelter,
        [Description("company headquarters")] company_headquarters,
        [Description("silo")] silo,
        [Description("waste incinerator")] waste_incinerator,
        [Description("gas station")] gas_station,
        [Description("hydrological station")] hydrological_station,
        [Description("mountain railway or chairlift station")] mountain_railway_chairlift_station,
        [Description("blood donation station")] blood_donation_station,
        [Description("meteorological station")] meteorological_station,
        [Description("radio and TV transmission station")] radio_and_tv_transmission_station,
        [Description("nautical station")] nautical_station,
        [Description("vehicle service station")] vehicle_service_station,
        [Description("fuel station")] fuel_station,
        [Description("pumping station")] pumping_station,
        [Description("sanitary-epidemiological station")] sanitary_epidemiological_station,
        [Description("transformer station")] transformer_station,
        [Description("stable")] stable,
        [Description("county office")] county_office,
        [Description("border guard")] border_guard,
        [Description("fire department")] fire_department,
        [Description("gendarmerie")] gendarmerie,
        [Description("synagogue")] synagogue, // synagogue
        [Description("greenhouse or hothouse")] greenhouse_or_hothouse, // greenhouse or hothouse
        [Description("primary school")] primary_school, // primary school
        [Description("secondary school")] secondary_school, // secondary school
        [Description("higher education institution or university")] higher_education_institution_or_university, // higher education institution or university
        [Description("hospital")] hospital, // hospital
        [Description("ice rink")] ice_rink, // ice rink
        [Description("theater")] theater, // theater
        [Description("port terminal")] port_terminal, // port terminal
        [Description("public toilet")] public_toilet, // public toilet
        [Description("riding hall")] riding_hall, // riding hall
        [Description("customs office")] customs_office, // customs office
        [Description("municipal office")] municipal_office, // municipal office
        [Description("marshal's office")] marshals_office, // marshal's office
        [Description("city hall")] city_hall, // city hall
        [Description("city and municipality office")] city_and_municipality_office, // city and municipality office
        [Description("voivodeship office")] voivodeship_office, // voivodeship office
        [Description("repair workshop")] repair_workshop, // repair workshop
        [Description("windmill")] windmill,
        [Description("barracks buildings")] barracks_buildings,
        [Description("monument not serving any functional purpose")] monument_not_serving_any_functional_purpose,
        [Description("inn")] inn,
        [Description("bus depot")] bus_depot,
        [Description("tram depot")] tram_depot,
        [Description("trolleybus depot")] trolleybus_depot,
        [Description("prison")] prison,
        [Description("prison or correctional facility")] prison_or_correctional_facility,
        [Description("correctional facility")] correctional_facility,
        [Description("liquid tank")] liquid_tank,
        [Description("gas tank")] gas_tank,
        [Description("nursery")] nursery,
    }
}
