using DiGi.BDOT10k.Enums;
using DiGi.Geo.Enums;
using System;

namespace DiGi.Geo
{
    public static partial class Convert
    {
        public static BuildingSpecificFunction ToDiGi(this OT_FunSzczegolowaBudynkuType oT_FunSzczegolowaBudynku)
        {
            return oT_FunSzczegolowaBudynku switch
            {
                OT_FunSzczegolowaBudynkuType.apteka => BuildingSpecificFunction.pharmacy,
                OT_FunSzczegolowaBudynkuType.archiwum => BuildingSpecificFunction.archive,
                OT_FunSzczegolowaBudynkuType.areszt_sledczy => BuildingSpecificFunction.remand_prison,
                OT_FunSzczegolowaBudynkuType.bacowka => BuildingSpecificFunction.shepherds_hut,
                OT_FunSzczegolowaBudynkuType.bank => BuildingSpecificFunction.bank,
                OT_FunSzczegolowaBudynkuType.basen_kapielowy => BuildingSpecificFunction.swimming_pool,
                OT_FunSzczegolowaBudynkuType.biblioteka => BuildingSpecificFunction.library,
                OT_FunSzczegolowaBudynkuType.budynek_gospodarczy => BuildingSpecificFunction.utility_building,
                OT_FunSzczegolowaBudynkuType.budynek_jednorodzinny => BuildingSpecificFunction.single_family_building,
                OT_FunSzczegolowaBudynkuType.budynek_kontroli_ruchu_kolejowego => BuildingSpecificFunction.railway_traffic_control_building,
                OT_FunSzczegolowaBudynkuType.budynek_kontroli_ruchu_powietrznego => BuildingSpecificFunction.air_traffic_control_building,
                OT_FunSzczegolowaBudynkuType.budynek_ogrodu_zoologicznego_lub_botanicznego => BuildingSpecificFunction.zoo_or_botanical_garden_building,
                OT_FunSzczegolowaBudynkuType.budynek_produkcyjny_zwierzat_hodowlanych => BuildingSpecificFunction.livestock_production_building,
                OT_FunSzczegolowaBudynkuType.budynek_spedycji => BuildingSpecificFunction.shipping_building,
                OT_FunSzczegolowaBudynkuType.budynek_wielorodzinny => BuildingSpecificFunction.multi_family_building,
                OT_FunSzczegolowaBudynkuType.budynki_cmentarne => BuildingSpecificFunction.cemetery_buildings,
                OT_FunSzczegolowaBudynkuType.centrum_handlowe => BuildingSpecificFunction.shopping_center,
                OT_FunSzczegolowaBudynkuType.centrum_informacyjne => BuildingSpecificFunction.information_center,
                OT_FunSzczegolowaBudynkuType.centrum_konferencyjne => BuildingSpecificFunction.conference_center,
                OT_FunSzczegolowaBudynkuType.centrum_telekomunikacyjne => BuildingSpecificFunction.telecommunications_center,
                OT_FunSzczegolowaBudynkuType.cerkiew => BuildingSpecificFunction.church,
                OT_FunSzczegolowaBudynkuType.chlodnia => BuildingSpecificFunction.cold_storage,
                OT_FunSzczegolowaBudynkuType.dom_dla_bezdomnych => BuildingSpecificFunction.homeless_shelter,
                OT_FunSzczegolowaBudynkuType.dom_dziecka => BuildingSpecificFunction.childrens_home,
                OT_FunSzczegolowaBudynkuType.dom_kultury => BuildingSpecificFunction.cultural_center,
                OT_FunSzczegolowaBudynkuType.dom_letniskowy => BuildingSpecificFunction.summer_house,
                OT_FunSzczegolowaBudynkuType.dom_opieki_spolecznej => BuildingSpecificFunction.social_care_home,
                OT_FunSzczegolowaBudynkuType.dom_parafialny => BuildingSpecificFunction.parish_house,
                OT_FunSzczegolowaBudynkuType.dom_pogrzebowy => BuildingSpecificFunction.funeral_home,
                OT_FunSzczegolowaBudynkuType.dom_rekolekcyjny => BuildingSpecificFunction.retreat_house,
                OT_FunSzczegolowaBudynkuType.dom_studencki => BuildingSpecificFunction.student_dormitory,
                OT_FunSzczegolowaBudynkuType.dom_towarowy_lub_handlowy => BuildingSpecificFunction.department_store,
                OT_FunSzczegolowaBudynkuType.dom_weselny => BuildingSpecificFunction.wedding_house,
                OT_FunSzczegolowaBudynkuType.dom_wypoczynkowy => BuildingSpecificFunction.holiday_house,
                OT_FunSzczegolowaBudynkuType.dom_zakonny => BuildingSpecificFunction.monastery_house,
                OT_FunSzczegolowaBudynkuType.domek_kempingowy => BuildingSpecificFunction.camping_cabin,
                OT_FunSzczegolowaBudynkuType.dworzec_autobusowy => BuildingSpecificFunction.bus_station,
                OT_FunSzczegolowaBudynkuType.dworzec_kolejowy => BuildingSpecificFunction.train_station,
                OT_FunSzczegolowaBudynkuType.dworzec_lotniczy => BuildingSpecificFunction.airport_terminal,
                OT_FunSzczegolowaBudynkuType.dzwonnica => BuildingSpecificFunction.bell_tower,
                OT_FunSzczegolowaBudynkuType.elektrocieplownia => BuildingSpecificFunction.combined_heat_power_plant,
                OT_FunSzczegolowaBudynkuType.elektrownia => BuildingSpecificFunction.power_plant,
                OT_FunSzczegolowaBudynkuType.elewator => BuildingSpecificFunction.grain_elevator,
                OT_FunSzczegolowaBudynkuType.filharmonia => BuildingSpecificFunction.philharmonic_hall,
                OT_FunSzczegolowaBudynkuType.galeria_sztuki => BuildingSpecificFunction.art_gallery,
                OT_FunSzczegolowaBudynkuType.garaz => BuildingSpecificFunction.garage,
                OT_FunSzczegolowaBudynkuType.hala_sportowa => BuildingSpecificFunction.sports_hall,
                OT_FunSzczegolowaBudynkuType.hala_targowa => BuildingSpecificFunction.market_hall,
                OT_FunSzczegolowaBudynkuType.hala_widowiskowa => BuildingSpecificFunction.arena,
                OT_FunSzczegolowaBudynkuType.hala_wystawowa => BuildingSpecificFunction.exhibition_hall,
                OT_FunSzczegolowaBudynkuType.halowy_tor_gokartowy => BuildingSpecificFunction.indoor_go_kart_track,
                OT_FunSzczegolowaBudynkuType.hangar => BuildingSpecificFunction.hangar,
                OT_FunSzczegolowaBudynkuType.hipermarket_lub_supermarket => BuildingSpecificFunction.hypermarket_or_supermarket,
                OT_FunSzczegolowaBudynkuType.hospicjum => BuildingSpecificFunction.hospice,
                OT_FunSzczegolowaBudynkuType.hotel => BuildingSpecificFunction.hotel,
                OT_FunSzczegolowaBudynkuType.hotel_robotniczy => BuildingSpecificFunction.workers_hotel,
                OT_FunSzczegolowaBudynkuType.inna_placowka_edukacyjna => BuildingSpecificFunction.other_educational_facility,
                OT_FunSzczegolowaBudynkuType.inny_budynek_kultu_religijnego => BuildingSpecificFunction.other_religious_building,
                OT_FunSzczegolowaBudynkuType.inny_urzad_administracji_publicznej => BuildingSpecificFunction.other_public_administration_office,
                OT_FunSzczegolowaBudynkuType.internat_lub_bursa_szkolna => BuildingSpecificFunction.boarding_school_dormitory,
                OT_FunSzczegolowaBudynkuType.izba_wytrzezwien => BuildingSpecificFunction.sobering_up_station,
                OT_FunSzczegolowaBudynkuType.jednostka_ratownictwa_medycznego => BuildingSpecificFunction.emergency_medical_service_unit,
                OT_FunSzczegolowaBudynkuType.kapitanat_lub_bosmanat_portu => BuildingSpecificFunction.port_authority_office,
                OT_FunSzczegolowaBudynkuType.kaplica => BuildingSpecificFunction.chapel,
                OT_FunSzczegolowaBudynkuType.kasyno => BuildingSpecificFunction.casino,
                OT_FunSzczegolowaBudynkuType.kino => BuildingSpecificFunction.cinema,
                OT_FunSzczegolowaBudynkuType.klasztor => BuildingSpecificFunction.monastery,
                OT_FunSzczegolowaBudynkuType.klinika_weterynaryjna => BuildingSpecificFunction.veterinary_clinic,
                OT_FunSzczegolowaBudynkuType.klub_sportowy => BuildingSpecificFunction.sports_club,
                OT_FunSzczegolowaBudynkuType.klub_dyskoteka => BuildingSpecificFunction.club_disco,
                OT_FunSzczegolowaBudynkuType.korty_tenisowe => BuildingSpecificFunction.tennis_courts,
                OT_FunSzczegolowaBudynkuType.koszary => BuildingSpecificFunction.barracks,
                OT_FunSzczegolowaBudynkuType.kosciol => BuildingSpecificFunction.church,
                OT_FunSzczegolowaBudynkuType.kotlownia => BuildingSpecificFunction.boiler_room,
                OT_FunSzczegolowaBudynkuType.krematorium => BuildingSpecificFunction.crematorium,
                OT_FunSzczegolowaBudynkuType.kregielnia => BuildingSpecificFunction.bowling_alley,
                OT_FunSzczegolowaBudynkuType.kuria_metropolitalna => BuildingSpecificFunction.metropolitan_curia,
                OT_FunSzczegolowaBudynkuType.latarnia_morska => BuildingSpecificFunction.lighthouse,
                OT_FunSzczegolowaBudynkuType.lesniczowka => BuildingSpecificFunction.foresters_lodge,
                OT_FunSzczegolowaBudynkuType.lokomotywownia_lub_wagonownia => BuildingSpecificFunction.locomotive_depot_carriage_shed,
                OT_FunSzczegolowaBudynkuType.magazyn => BuildingSpecificFunction.warehouse,
                OT_FunSzczegolowaBudynkuType.meczet => BuildingSpecificFunction.mosque,
                OT_FunSzczegolowaBudynkuType.ministerstwo => BuildingSpecificFunction.ministry_building,
                OT_FunSzczegolowaBudynkuType.mlyn => BuildingSpecificFunction.mill,
                OT_FunSzczegolowaBudynkuType.motel => BuildingSpecificFunction.motel,
                OT_FunSzczegolowaBudynkuType.muzeum => BuildingSpecificFunction.museum,
                OT_FunSzczegolowaBudynkuType.myjnia_samochodowa => BuildingSpecificFunction.car_wash,
                OT_FunSzczegolowaBudynkuType.obserwatorium_lub_planetarium => BuildingSpecificFunction.observatory_or_planetarium,
                OT_FunSzczegolowaBudynkuType.opera => BuildingSpecificFunction.opera_house,
                OT_FunSzczegolowaBudynkuType.osrodek_pomocy_spolecznej => BuildingSpecificFunction.social_welfare_center,
                OT_FunSzczegolowaBudynkuType.osrodek_szkoleniowo_wypoczynkowy => BuildingSpecificFunction.training_leisure_center,
                OT_FunSzczegolowaBudynkuType.parking_wielopoziomowy => BuildingSpecificFunction.multi_story_parking_garage,
                OT_FunSzczegolowaBudynkuType.obiekt_handlowo_uslugowy => BuildingSpecificFunction.commercial_service_building,
                OT_FunSzczegolowaBudynkuType.pawilon_ogrodowy_lub_oranzeria => BuildingSpecificFunction.garden_pavilion_orangery,
                OT_FunSzczegolowaBudynkuType.pensjonat => BuildingSpecificFunction.guesthouse,
                OT_FunSzczegolowaBudynkuType.placowka_badawcza => BuildingSpecificFunction.research_facility,
                OT_FunSzczegolowaBudynkuType.placowka_dyplomatyczna_lub_konsularna => BuildingSpecificFunction.diplomatic_or_consular_office,
                OT_FunSzczegolowaBudynkuType.placowka_ochrony_zdrowia => BuildingSpecificFunction.healthcare_facility,
                OT_FunSzczegolowaBudynkuType.placowka_operatora_pocztowego => BuildingSpecificFunction.postal_operators_office,
                OT_FunSzczegolowaBudynkuType.placowka_opiekunczo_wychowawcza => BuildingSpecificFunction.care_educational_facility,
                OT_FunSzczegolowaBudynkuType.policja => BuildingSpecificFunction.police_station,
                OT_FunSzczegolowaBudynkuType.produkcyjny => BuildingSpecificFunction.production_building,
                OT_FunSzczegolowaBudynkuType.prokuratura => BuildingSpecificFunction.prosecutors_office,
                OT_FunSzczegolowaBudynkuType.przedszkole => BuildingSpecificFunction.kindergarten,
                OT_FunSzczegolowaBudynkuType.przejscie_graniczne => BuildingSpecificFunction.border_crossing,
                OT_FunSzczegolowaBudynkuType.rafineria => BuildingSpecificFunction.refinery,
                OT_FunSzczegolowaBudynkuType.restauracja => BuildingSpecificFunction.restaurant,
                OT_FunSzczegolowaBudynkuType.rezydencja_ambasadora => BuildingSpecificFunction.ambassadors_residence,
                OT_FunSzczegolowaBudynkuType.rezydencja_biskupia => BuildingSpecificFunction.bishops_residence,
                OT_FunSzczegolowaBudynkuType.rezydencja_prezydencka => BuildingSpecificFunction.presidential_residence,
                OT_FunSzczegolowaBudynkuType.sala_gimnastyczna => BuildingSpecificFunction.gym,
                OT_FunSzczegolowaBudynkuType.sanatorium => BuildingSpecificFunction.solarium,
                OT_FunSzczegolowaBudynkuType.sad => BuildingSpecificFunction.court_building,
                OT_FunSzczegolowaBudynkuType.schronisko_dla_nieletnich => BuildingSpecificFunction.juvenile_shelter,
                OT_FunSzczegolowaBudynkuType.schronisko_dla_zwierzat => BuildingSpecificFunction.animal_shelter,
                OT_FunSzczegolowaBudynkuType.schronisko_turystyczne => BuildingSpecificFunction.tourist_shelter,
                OT_FunSzczegolowaBudynkuType.siedziba_firmy_lub_firm => BuildingSpecificFunction.company_headquarters,
                OT_FunSzczegolowaBudynkuType.silos => BuildingSpecificFunction.silo,
                OT_FunSzczegolowaBudynkuType.spalarnia_smieci => BuildingSpecificFunction.waste_incinerator,
                OT_FunSzczegolowaBudynkuType.stacja_gazowa => BuildingSpecificFunction.gas_station,
                OT_FunSzczegolowaBudynkuType.stacja_hydrologiczna => BuildingSpecificFunction.hydrological_station,
                OT_FunSzczegolowaBudynkuType.stacja_kolejki_gorskiej_lub_wyciagu_krzeselkowego => BuildingSpecificFunction.mountain_railway_chairlift_station,
                OT_FunSzczegolowaBudynkuType.stacja_krwiodawstwa => BuildingSpecificFunction.blood_donation_station,
                OT_FunSzczegolowaBudynkuType.stacja_meteorologiczna => BuildingSpecificFunction.meteorological_station,
                OT_FunSzczegolowaBudynkuType.stacja_nadawcza_radia_i_telewizji => BuildingSpecificFunction.radio_and_tv_transmission_station,
                OT_FunSzczegolowaBudynkuType.stacja_nautyczna => BuildingSpecificFunction.nautical_station,
                OT_FunSzczegolowaBudynkuType.stacja_obslugi_pojazdow => BuildingSpecificFunction.vehicle_service_station,
                OT_FunSzczegolowaBudynkuType.stacja_paliw => BuildingSpecificFunction.fuel_station,
                OT_FunSzczegolowaBudynkuType.stacja_pomp => BuildingSpecificFunction.pumping_station,
                OT_FunSzczegolowaBudynkuType.stacja_sanitarno_epidemiologiczna => BuildingSpecificFunction.sanitary_epidemiological_station,
                OT_FunSzczegolowaBudynkuType.stacja_transformatorowa => BuildingSpecificFunction.transformer_station,
                OT_FunSzczegolowaBudynkuType.stajnia => BuildingSpecificFunction.stable,
                OT_FunSzczegolowaBudynkuType.starostwo_powiatowe => BuildingSpecificFunction.county_office,
                OT_FunSzczegolowaBudynkuType.straz_graniczna => BuildingSpecificFunction.border_guard,
                OT_FunSzczegolowaBudynkuType.straz_pozarna => BuildingSpecificFunction.fire_department,
                OT_FunSzczegolowaBudynkuType.strzelnica => BuildingSpecificFunction.gendarmerie,
                OT_FunSzczegolowaBudynkuType.synagoga => BuildingSpecificFunction.synagogue,
                OT_FunSzczegolowaBudynkuType.szklarnia_lub_cieplarnia => BuildingSpecificFunction.greenhouse_or_hothouse,
                OT_FunSzczegolowaBudynkuType.szkola_podstawowa => BuildingSpecificFunction.primary_school,
                OT_FunSzczegolowaBudynkuType.szkola_ponadpodstawowa => BuildingSpecificFunction.secondary_school,
                OT_FunSzczegolowaBudynkuType.szkoła_wyzsza => BuildingSpecificFunction.higher_education_institution_or_university,
                OT_FunSzczegolowaBudynkuType.szpital => BuildingSpecificFunction.hospital,
                OT_FunSzczegolowaBudynkuType.sztuczne_lodowisko => BuildingSpecificFunction.ice_rink,
                OT_FunSzczegolowaBudynkuType.teatr => BuildingSpecificFunction.theater,
                OT_FunSzczegolowaBudynkuType.terminal_portowy => BuildingSpecificFunction.port_terminal,
                OT_FunSzczegolowaBudynkuType.toaleta_publiczna => BuildingSpecificFunction.public_toilet,
                OT_FunSzczegolowaBudynkuType.ujezdzalnia => BuildingSpecificFunction.riding_hall,
                OT_FunSzczegolowaBudynkuType.urzad_celny => BuildingSpecificFunction.customs_office,
                OT_FunSzczegolowaBudynkuType.urzad_gminy => BuildingSpecificFunction.municipal_office,
                OT_FunSzczegolowaBudynkuType.urzad_marszalkowski => BuildingSpecificFunction.marshals_office,
                OT_FunSzczegolowaBudynkuType.urzad_miasta => BuildingSpecificFunction.city_hall,
                OT_FunSzczegolowaBudynkuType.urzad_miasta_i_gminy => BuildingSpecificFunction.city_and_municipality_office,
                OT_FunSzczegolowaBudynkuType.urzad_wojewodzki => BuildingSpecificFunction.voivodeship_office,
                OT_FunSzczegolowaBudynkuType.warsztat_remontowo_naprawczy => BuildingSpecificFunction.repair_workshop,
                OT_FunSzczegolowaBudynkuType.wiatrak => BuildingSpecificFunction.windmill,
                OT_FunSzczegolowaBudynkuType.zabudowania_koszarowe => BuildingSpecificFunction.barracks_buildings,
                OT_FunSzczegolowaBudynkuType.zabytek_niepelniacy_zadnej_funkcji_uzytkowej => BuildingSpecificFunction.monument_not_serving_any_functional_purpose,
                OT_FunSzczegolowaBudynkuType.zajazd => BuildingSpecificFunction.inn,
                OT_FunSzczegolowaBudynkuType.zajezdnia_autobusowa => BuildingSpecificFunction.bus_depot,
                OT_FunSzczegolowaBudynkuType.zajezdnia_tramwajowa => BuildingSpecificFunction.tram_depot,
                OT_FunSzczegolowaBudynkuType.zajezdnia_trolejbusowa => BuildingSpecificFunction.trolleybus_depot,
                OT_FunSzczegolowaBudynkuType.zaklad_karny => BuildingSpecificFunction.prison,
                OT_FunSzczegolowaBudynkuType.zaklad_karny_lub_poprawczy => BuildingSpecificFunction.prison_or_correctional_facility,
                OT_FunSzczegolowaBudynkuType.zaklad_poprawczy => BuildingSpecificFunction.correctional_facility,
                OT_FunSzczegolowaBudynkuType.zbiornik_na_ciecz => BuildingSpecificFunction.liquid_tank,
                OT_FunSzczegolowaBudynkuType.zbiornik_na_gaz => BuildingSpecificFunction.gas_tank,
                OT_FunSzczegolowaBudynkuType.zlobek => BuildingSpecificFunction.nursery,
                _ => throw new NotImplementedException(),
            };
        }
    }
}


